apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: frontend
  name: frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      service: frontend
  template:
    metadata:
      labels:
        service: frontend
        api: external
    spec:
      containers:
        - image: faeshaas/udagram-frontend:v1
          name: frontend
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          resources:
            requests:
              memory: '128Mi'
              cpu: '250m'
            limits:
              memory: '2048Mi'
              cpu: '500m'
      restartPolicy: Always
